version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file:
      - ./docker/env
      - ./docker/app/env
    build: ./docker/app
    networks:
      - db_network
      - web_network
    volumes:
      - ~/IDASH/Webdav/data:/var/www/html/webdav
    stdin_open: true # interaction option

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
    stdin_open: true # interaction option

  db:
    container_name: IDASH-mariadb
    build: ./docker/mariadb
    init: true
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./docker/env
      - ./docker/mariadb/env

    networks:
      - db_network

    volumes:
      - ~/IDASH/MariaDB/data:/var/lib/mysql
      - ~/IDASH/MariaDB/setting:/etc/mysql/conf.d
      - ./docker/mariadb/sql:/docker-entrypoint-initdb.d
      
    ports:
      - "33061:3306"
    stdin_open: true # interaction option

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge


 