version: '3.8'
services:

  appseed-app:
    image: "nginx:latest"
    container_name: appseed_app
    restart: always
    env_file:
      - ./docker/env
      - ./docker/app/env
    build: ./docker/app
    networks:
      - db_network
      - web_network
    volumes:
      - ./IDASH/Webdav/data:/var/www/html/webdav
    stdin_open: true # interaction option

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
    stdin_open: true # interaction option

  db:
    image: mariadb:latest
    container_name: IDASH-mariadb
    env_file:
      - ./docker/env
      - ./docker/app/env
    networks:
      - db_network
    restart: always
    volumes:
      - ./IDASH/MariaDB/data:/var/lib/mysql
      - ./IDASH/MariaDB/setting:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    stdin_open: true # interaction option

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge


 