version: '3.8'
services:
  db:
    container_name: IDASH-mariadb-test
    build: .
    init: true
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    
    env_file:
      - ./env

    restart: always

    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./test:/test
      
    ports:
      - "33062:3306"
    stdin_open: true # interaction option



 