version: '3.8'
services:
  db:
    container_name: IDASH-mariadb-test
    build: .
    user: $UID:$GID
    init: true
    command: 
    #   - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      # - --range_optimizer_max_mem_size=16777216
    
    env_file:
      - ./env

    restart: always
    # volumes:
      # - ~/IDASH/MariaDB/data:/var/lib/mysql
      # - ~/IDASH/MariaDB/setting:/etc/mysql/conf.d
      # - ./IDASH/MariaDB/initdb.d:/docker-entrypoint-initdb.d
      
    ports:
      - "33062:3306"
    stdin_open: true # interaction option



 