CREATE DATABASE mdash;
use mdash;
CREATE TABLE USERS(ID INT, NAME VARCHAR(128));

INSERT INTO USERS(ID, NAME) VALUES(1, 'aa1');
INSERT INTO USERS(ID, NAME) VALUES(2, 'bb2');
INSERT INTO USERS(ID, NAME) VALUES(3, 'cc3');
INSERT INTO USERS(ID, NAME) VALUES(4, 'dd4');
INSERT INTO USERS(ID, NAME) VALUES(5, 'ee5');
INSERT INTO USERS(ID, NAME) VALUES(6, 'ff6');
commit;
-- LOAD DATA INFILE './departments.csv' INTO TABLE departments FIELDS TERMINATED BY ',' (`name`, `priority`);